# Generated by Django 6.0.3 on 2026-04-17 19:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('calories', models.IntegerField(help_text='Calories per 100g')),
                ('protein', models.FloatField(default=0.0)),
                ('carbs', models.FloatField(default=0.0)),
                ('fats', models.FloatField(default=0.0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='foods/')),
            ],
        ),
        migrations.CreateModel(
            name='FoodAlternative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason_why', models.TextField()),
                ('original_food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternatives', to='dataAboutUser.food')),
                ('suggested_alternative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitutes', to='dataAboutUser.food')),
            ],
        ),
        migrations.CreateModel(
            name='HealthProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.FloatField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('has_diabetes', models.BooleanField(default=False)),
                ('has_blood_pressure', models.BooleanField(default=False)),
                ('has_lactose_allergy', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ScanHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=255)),
                ('calories', models.FloatField()),
                ('protein', models.FloatField()),
                ('carbs', models.FloatField()),
                ('fats', models.FloatField()),
                ('is_healthy', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='scans/')),
                ('scan_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_feedback', models.TextField()),
                ('health_score', models.IntegerField(blank=True, null=True)),
                ('is_safe', models.BooleanField(default=True)),
                ('scan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dataAboutUser.scanhistory')),
            ],
        ),
    ]
