# Generated by Django 6.0.2 on 2026-03-12 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataAboutUser', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthprofile',
            name='chronic_diseases',
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='daily_calories_goal',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='healthprofile',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='healthprofile',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
