# Generated by Django 6.0.3 on 2026-04-17 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataAboutUser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='foods/'),
        ),
    ]
