# Generated by Django 6.0.3 on 2026-04-17 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataAboutUser', '0002_auto_20260417_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanhistory',
            name='suggested_alternative',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
