# Generated by Django 6.0.3 on 2026-04-07 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataAboutUser', '0002_remove_healthprofile_chronic_diseases_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthprofile',
            name='chronic_diseases',
            field=models.TextField(blank=True, null=True, verbose_name='أمراض مزمنة أخرى'),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='food_allergies',
            field=models.TextField(blank=True, null=True, verbose_name='حساسية طعام'),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='has_blood_pressure',
            field=models.BooleanField(default=False, verbose_name='ضغط'),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='has_diabetes',
            field=models.BooleanField(default=False, verbose_name='سكر'),
        ),
    ]
