# Generated by Django 6.0.3 on 2026-04-17 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataAboutUser', '0003_scanhistory_suggested_alternative'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnalysisResult',
        ),
    ]
