# Generated by Django 6.0.3 on 2026-04-15 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataAboutUser', '0003_healthprofile_chronic_diseases_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='ingredients',
            field=models.TextField(blank=True, null=True),
        ),
    ]
