# Generated by Django 6.0.3 on 2026-04-15 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataAboutUser', '0004_food_ingredients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='ingredients',
        ),
    ]
